// Package cliinit emits the shell snippets that `konch init <shell>`
// prints to stdout. Users wire them into their shellrc with `eval`:
//
//	eval "$(konch init bash)"
//
// After that, `kubectl exec -it <pod> -- bash` (and equivalent shapes)
// transparently routes through `konch <pod>`. Other kubectl invocations
// pass through unmodified.
//
// v0.2 phase A ships only Bash. Phase B adds Zsh and Fish.
package cliinit

// Bash returns the bash wrapper snippet. The snippet declares a
// `kubectl()` function that inspects argv:
//
//   - If it looks like `kubectl [<flags>] exec [<flags>] <pod> [-c <c>] [-n <ns>] -- <shell>?`,
//     run `command konch <pod> [--container <c>] [--namespace <ns>] [--context <ctx>]`.
//   - Otherwise fall through to `command kubectl "$@"`.
//
// The shape match is intentionally narrow: post-`--` must be empty or a
// bare shell name (bash, sh, zsh, fish, or absolute-pathed equivalents),
// with no extra args. `kubectl exec pod -- bash -c '...'` is one-shot,
// not interactive, and gets passed through.
func Bash() string { return bashSnippet }

// HEADER explains the snippet to anyone reading their own shellrc.
// Keep it short — it shows up every time someone runs `konch init bash`.
const header = "# konch: transparent kubectl-exec wrapper. Generated by konch init bash.\n" +
	"# Source via: eval \"$(konch init bash)\"\n"

const bashSnippet = header + `
kubectl() {
  local saw_exec=0 pod="" lead i=1
  local opts=() trailing=()
  while [ $i -le $# ]; do
    local a="${!i}"
    if [ "$a" = "--" ]; then
      i=$((i+1))
      while [ $i -le $# ]; do
        trailing+=("${!i}")
        i=$((i+1))
      done
      break
    fi
    case "$a" in
      exec) saw_exec=1 ;;
      -c|--container) i=$((i+1)); opts+=("--container" "${!i}") ;;
      --container=*) opts+=("--container" "${a#--container=}") ;;
      -n|--namespace) i=$((i+1)); opts+=("--namespace" "${!i}") ;;
      --namespace=*) opts+=("--namespace" "${a#--namespace=}") ;;
      --context) i=$((i+1)); opts+=("--context" "${!i}") ;;
      --context=*) opts+=("--context" "${a#--context=}") ;;
      -*) ;;
      *) [ $saw_exec -eq 1 ] && [ -z "$pod" ] && pod="$a" ;;
    esac
    i=$((i+1))
  done

  if [ $saw_exec -eq 1 ] && [ -n "$pod" ] && [ ${#trailing[@]} -le 1 ]; then
    lead="${trailing[0]:-}"
    case "$lead" in
      "" | bash | sh | zsh | fish | /bin/bash | /bin/sh | /bin/zsh | /usr/bin/fish | /usr/local/bin/fish)
        command konch "$pod" "${opts[@]}"
        return $?
        ;;
    esac
  fi
  command kubectl "$@"
}
`
